version: "3.3"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: axionet
    ports:
      - "5436:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

volumes:
  db:
